import java.awt.Point;
import java.util.ArrayList;
import javafx.util.Pair;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author markn
 */
public class DrawScreen extends javax.swing.JFrame {

    /**
     * Creates new form gfxTest
     * @param graphData
     */
    public DrawScreen(GraphGeorge graphData) 
    {
        initComponents();
        setExtendedState(DrawScreen.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        ArrayList<Pair<Integer, Integer>> edgesList = new ArrayList<>();
        for (int i=0 ; i<graphData.Edges.size() ; i++)
        {
            edgesList.add(new Pair(graphData.Edges.get(i).From, graphData.Edges.get(i).To));
        }
        Graph graph = new Graph(graphData.numberOfNodes, edgesList, true, graphDrawingPanel);
        graph.DrawGraph();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphDrawingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        graphDrawingPanel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout graphDrawingPanelLayout = new javax.swing.GroupLayout(graphDrawingPanel);
        graphDrawingPanel.setLayout(graphDrawingPanelLayout);
        graphDrawingPanelLayout.setHorizontalGroup(
            graphDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        graphDrawingPanelLayout.setVerticalGroup(
            graphDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphDrawingPanel;
    // End of variables declaration//GEN-END:variables
}
